# 테스트 완료


GET https://back.exitgift.shop:4000/art

###

GET https://back.exitgift.shop:4000/art/5359fc48-d8be-4f80-a3d9-9759c541e772


###

GET https://back.exitgift.shop:4000/art/user/82865d2f-26b8-4611-85f1-933643995e79

###


POST https://back.exitgift.shop:4000/art
content-type: application/json

{
  "file_id": "1",
  "artist_uuid": "82865d2f-26b8-4611-85f1-933643995e79",
  "title":"testTitle0",
  "desc":"testDesc2",
  "twitter":"testDesc3"
}

###

PUT https://back.exitgift.shop:4000/art/5359fc48-d8be-4f80-a3d9-9759c541e772
content-type: application/json

  # "file_id": "2",
  # "title":"testTitleaaaaaaa",
  # "artist_uuid": "82865d2f-26b8-4611-85f1-933643995e79",
  # "twitter":"twittertestestestestt",
{
  "desc":"testDescaaaaa"
}

###

DELETE https://back.exitgift.shop:4000/art/5359fc48-d8be-4f80-a3d9-9759c541e772

